### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by juliandesmarais** [lukasz-aw/moxproxy#19]
I'm using the latest release and the README doesn't line up. The latest release is 1.1.2.

```
        <dependency>
            <groupId>com.moxproxy</groupId>
            <artifactId>moxproxy.core</artifactId>
            <version>1.1.2</version>
        </dependency>
```

For example, there is no `MoxProxy` class in 1.1.2.

**Comment by lukasz-aw** [comment]
I updated README with latest version but there is no API change in this release. MoxProxy is (and always was) an interface and is still present - please doublecheck.
