### ISSUE TITLE
BUG-001-Unable to modify request

### ISSUE THREAD

**Issue by emukhin** [lukasz-aw/moxproxy#8]
I'm trying to achieve request body modification.

String body = "{ololo}";

A rule looks as follows:

MoxProxyRule rule = MoxProxyRule.builder()
                .withDirection(MoxProxyDirection.REQUEST)
                .withAction(MoxProxyAction.MODIFY)
                .withSessionId(sessionId)
                .withHttpRuleDefinition()
                    .withPathPattern("token$")
                    .withPostMethod()
                    .withBody(body)
                    .backToParent()
                .build();

moxProxyClient.getSessionRequestTraffic(sessionId) shows that body is not  "{ololo}" but has its original value.

**Comment by lukasz-aw** [comment]
Traffic recorder always records original traffic that enters proxy. 
Please check the proxy logs to see if modification has been applied. You should see such log:
_Setting request body: {} for path {} and method {}_

If your modification has not been applied at all, then please sent me complete code of your case - will try to reproduce.

At the moment proxy does not have a feature to collect also applied modifications - i can think about it if you need.

**Comment by emukhin** [comment]
Alright. I see. I also checked it directly in a browser on network tab in dev tools. 
I suspect I might have messed with a path pattern. Couldn't find a good example of what I should put there. 
Can it be just a full url like "https://site.com/book/v1/token"

**Comment by lukasz-aw** [comment]
Please note that browser is a web client and browser is initiating the request. Proxy is in the middle so you cannot see request modification in dev tools.

Browser - > proxy - > server

You might also need to modify request header   Content-Length with new lenght of the body if its different than original.

**Comment by emukhin** [comment]
Oh, that makes sense. Will try it tomorrow and let you know.

**Comment by emukhin** [comment]
Still trying to figure it out. In order to check that post parameters are really being replaced I created a page on my own server on which I call $.ajax post request after clicking submit button. This request is not intercepted by the proxy i.e. moxProxyClient.getSessionRequestTraffic(sessionId) is empty. Am I doing something wrong?

**Comment by lukasz-aw** [comment]
I'm investigating. Will get back to you

**Comment by lukasz-aw** [comment]
Ok, I can see there is a bug in request body modification. Will fix and release new version tonight.

**Comment by lukasz-aw** [comment]
Fix for the request body modification issue has been deployed to Maven central in release 1.0.4. 
Standalone proxy server can be found under [Releases](https://github.com/lukasz-aw/moxproxy/releases/tag/moxproxy-1.0.4).

For session id matching problem, please make sure:
* your proxy service or standalone service has session id matchin strategy enabled
* you include session id in your cookie (for webdriver)
* you include session id in MoxProxy rule (.withSessionId(sessionId)

Please let me know whether applied change resolved your issue.

**Comment by emukhin** [comment]
Seems like it didn't help. I see no traffic being captured in the log

Here's my sample code.

@Test
public void proxyModify() throws UnsupportedEncodingException, InterruptedException {

	String captchaResponse = "OLOLO";
	String body = "{\"token\": \""+captchaResponse+"\"}";
	int contentLength = body.getBytes("UTF-8").length;
	String sessionId = UUID.randomUUID().toString();

	MoxProxyService moxProxyClient = MoxProxyClient.builder()
			.withBaseUrl("http://bookroadtest:8088")
			.withUser("change-user")
			.withPassword("change-password").build();

	MoxProxyRule rule = MoxProxyRule.builder()
			.withDirection(MoxProxyDirection.REQUEST)
			.withAction(MoxProxyAction.MODIFY)
			.withSessionId(sessionId)
			.withHttpRuleDefinition()
				.withPathPattern("https://bookroadtest.ca/captcha")
				.withPostMethod()
				.withBody(body)
				.havingHeaders()
					.withHeader("Content-Length", contentLength)
					.backToParent()
				.backToParent()
			.build();

	moxProxyClient.createRule(rule);

	try {
		BrowserSession.startBrowserSession();
		WebDriver driver = BrowserSession.getWebDriver();
		Cookie cookie = new Cookie("MOXSESSIONID", sessionId);
		driver.get("https://bookroadtest.ca/captcha");
		Thread.sleep(2000);
		driver.findElement(By.cssSelector("#submit")).click();
		driver.manage().addCookie(cookie);
		List<MoxProxyProcessedTrafficEntry> requestTraffic = moxProxyClient.getSessionRequestTraffic(sessionId);
		List<MoxProxyProcessedTrafficEntry> responseTraffic = moxProxyClient.getSessionResponseTraffic(sessionId);
	} finally {
		BrowserSession.closeBrowserSession();
	}
}

**Comment by lukasz-aw** [comment]
You ate adding cookie after click. Cookie should be the first think added.
1. Go to url
2. Add cookie
3. Go to url aggain
4. Click
5. Get traffic

**Comment by emukhin** [comment]
Alright. It wasn't that clear from the documentation. 
So now I see traffic but only from GET requests. POST request after clicking submit is not being intercepted. I suppose it should be the opposite. Due to the rule there should not be any GET traffic.

**Comment by lukasz-aw** [comment]
Is post request domain different than the one set for cookie? Webdriver can set a cookie only for domain it is navigated to. So if your post goes somewhere else then session id will not be send within cookie.
If its the case I would recommend turning off session id matching strategy or start proxy as local service on the specific port for this test session. Turning off session id matching strategy for standalone proxy is just a change i application.yml config file - see readme.

**Comment by lukasz-aw** [comment]
Traffic recorder records everything that goes through proxy. Rules are used only to setup request/response modification. So if you get traffic it will return everything that was recorded for session id.

**Comment by emukhin** [comment]
Yes the domain was different. I did as you suggested and it's working. Thank you!

**Comment by lukasz-aw** [comment]
Great, have fun and don't hesitate to let me know if you encounter any issues. Thanks
